let countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Angola",
    "Armenia",
    "Bangladesh",
    "Barbados",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Botswana",
    "Brunei",
    "Burkina",
    "Burma",
    "Myanmar",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "Democratic Republic of Congo",
    "Djibouti",
    "Dominica",
    "East Timor",
    "Equatorial Guinea",
    "Eritrea",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Grenada",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Iceland",
    "Iran",
    "Iraq",
    "Ivory Coast",
    "Jamaica",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "North Korea",
    "Kyrgyzstan",
    "Laos",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Maldives",
    "Mali",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Micronesia",
    "Mongolia",
    "Montenegro",
    "Mozambique",
    "Namibia",
    "Nauru",
    "Nepal",
    "Niger",
    "Nigeria",
    "Palau",
    "Papua New Guinea",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Sao Tome and Principe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Solomon Islands",
    "Somalia",
    "South Sudan",
    "Sudan",
    "Swaziland",
    "Syria",
    "Tajikistan",
    "Togo",
    "Tonga",
    "Tunisia",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Uzbekistan",
    "Vanuatu",
    "Yemen",
    "Zimbabwe"
]

export default countries